/'
AutonomousProxy での CurrentWeapon の初期化
Case2 Inventory -> PlayerState の順にレプリケーションされた（ RPC のほうが早かった）場合
'/
@startuml CurrentWeapon-Initialize-AutonomousProxy-Case1
autoactivate on
Authority -> AutonomousProxy : replicate Inventory
return
hnote over AutonomousProxy #FFAAAA: sync Inventory with server
AutonomousProxy -> AutonomousProxy : OnRep_Inventory
AutonomousProxy -> AutonomousProxy : RPCServerSyncCurrentWeapon()
return
return

AutonomousProxy -> Authority: rpc RPCServerSyncCurrentWeapon()
return

Authority -> Authority : RPCServerSyncCurrentWeapon()
Authority -> Authority : RPCClientSyncCurrentWeapon(CurrentWeapon)
return
return

rnote over Authority : InWeapon = CurrentWeapon
hnote over Authority #AAFFAA: RPCClient*** will only send to autonomous actors.
Authority -> AutonomousProxy: rpc RPCClientSyncCurrentWeapon(InWeapon)
return

AutonomousProxy -> AutonomousProxy: RPCClientSyncCurrentWeapon(InWeapon)
rnote over AutonomousProxy
LastWeapon = CurrentWeapon
CurrentWeapon = InWeapon
end rnote
hnote over AutonomousProxy #FFAAAA: sync CurrentWeapon with server
AutonomousProxy -> AutonomousProxy: OnRep_CurrentWeapon(LastWeapon)
rnote over AutonomousProxy : bChangedWeaponLocally = false
AutonomousProxy -> AutonomousProxy: SetCurrentWeapon(CurrentWeapon)
hnote over AutonomousProxy #AAAAFF: PlayerState and ASC is not active
return
return
return

Authority -> AutonomousProxy : replicate PlayerState
return
hnote over AutonomousProxy #FFAAAA: sync PlayerState with server
AutonomousProxy -> AutonomousProxy : OnRep_PlayerState
rnote over AutonomousProxy : set CurrentWeapon's owner,\nASC delegates and GameplayTags.
return
@enduml
