/'
SimulatedProxy での CurrentWeapon の初期化
Case2 CurrentWeapon -> PlayerState の順にレプリケーションされた場合
'/
@startuml CurrentWeapon-Initialize-SimulatedProxy-Case1
autoactivate on
hnote over Authority #AAFFAA: CurrentWeapon will only send to simulated actors.
Authority -> SimulatedProxy: replicate CurrentWeapon
return
hnote over SimulatedProxy #FFAAAA: sync CurrentWeapon with Authority
SimulatedProxy -> SimulatedProxy: OnRep_CurrentWeapon(LastWeapon)
rnote over SimulatedProxy : bChangedWeaponLocally = false
SimulatedProxy -> SimulatedProxy: SetCurrentWeapon(CurrentWeapon)
hnote over SimulatedProxy #AAAAFF: PlayerState and ASC is not active
return
return
|||
Authority -> SimulatedProxy : replicate PlayerState
return
hnote over SimulatedProxy #FFAAAA: sync PlayerState with Authority
SimulatedProxy -> SimulatedProxy : OnRep_PlayerState
rnote over SimulatedProxy : set CurrentWeapon's owner,\nASC delegates and GameplayTags.
return
|||
Authority -> SimulatedProxy : replicate Inventory
return
hnote over SimulatedProxy #FFAAAA: sync Inventory with Authority
SimulatedProxy -> SimulatedProxy : OnRep_Inventory
return

@enduml
